Concatenate


In [22]:
import numpy as np

In [23]:
list1 = [1,2,3,4]
list2 = [10,11,23,45]

np.concatenate((list1, list2))

array([ 1,  2,  3,  4, 10, 11, 23, 45])

In [24]:
# Horizontal Concatentate
np.hstack((list1,list2))

array([ 1,  2,  3,  4, 10, 11, 23, 45])

In [25]:
# Vertical Concatenate
np.vstack((list1, list2))

array([[ 1,  2,  3,  4],
       [10, 11, 23, 45]])

Split

In [45]:
d1 = np.array([4,6,1,3,5,10,14,15])
np.split(d1,[1,3])

[array([4]), array([6, 1]), array([ 3,  5, 10, 14, 15])]