Mathematical Operation using Numpy

In [4]:
import numpy as np
arr1 = np.arange(1,10).reshape(3,3)
arr2 = np.arange(1,10).reshape(3,3)
print(arr1)
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


Addition

In [6]:
# addition element wise
arr1 + arr2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

Substraction

In [20]:
# Substract
out = arr2 - arr1
print("The substraciton is: \n", out)
np.subtract(arr1, arr2)

The substraciton is: 
 [[0 0 0]
 [0 0 0]
 [0 0 0]]


array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [21]:
np.divide(arr1, arr2)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

Multiply

In [22]:
# Multiply
mul = np.multiply(arr1, arr2)
print(mul)

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [24]:
mul2 = arr1 @ arr2
print(mul2)

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


In [25]:
arr1.dot(arr2)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

Divide


In [26]:
div = arr1 / arr2
print(div)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


Find max value


In [28]:
arr1.max()


9

In [31]:
# to find the index of maximum numebr
arr1.argmax()

8

In [36]:
# To find the max row number or col number
# axis = 0 for 'col' and axis = 1 for 'row'
arr1.max(axis = 0)

array([7, 8, 9])

In [38]:
# find the minimum value
arr1.min()

1

In [39]:
# find the min  value index
arr1.argmin()

0

In [41]:
# find the min col value
arr1.min(axis = 0)

array([1, 2, 3])

In [43]:
# Add all value of arr1
np.sum(arr1)

45

In [44]:
# add all the number in row axis
np.sum(arr1, axis=1)

array([ 6, 15, 24])

In [45]:
# add all the number in col axis
np.sum(arr1, axis=0)

array([12, 15, 18])

In [46]:
# avaergae
np.min(arr1)

1

In [47]:
# Find sq root
np.sqrt(arr1)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [48]:
np.std(arr1)

2.581988897471611

In [52]:
# exponential
np.exp(arr1)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [50]:
# log
np.log(arr1)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [51]:
np.log10(arr1)

array([[0.        , 0.30103   , 0.47712125],
       [0.60205999, 0.69897   , 0.77815125],
       [0.84509804, 0.90308999, 0.95424251]])