NUMPY FUNCTION

In [11]:
# Arange Function
import numpy as np
# np.arange(start,end,step)
a = np.arange(1,13)
print(a);

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [7]:
# linspace
np.linspace(0,12,3)

array([ 0.,  6., 12.])

In [18]:
# Reshape to 2D array
t2d = a.reshape(6,2)
print(t2d);

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [20]:
# Reshape to 3D array
t3d = a.reshape(2,3,2)
print(t3d)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [23]:
# reshape 3d into 3d 
tre2 = np.arange(1,13).reshape(2,6)
print(tre2)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [26]:
# ravel function
t3d.ravel()
# Multidimentional array into 1d array


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [27]:
# flatten
t3d.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [29]:
# transpose/T
tre2.transpose()

array([[ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11],
       [ 6, 12]])