In [1]:
import numpy as np
arr_1d = np.array([1,2,3,4])
print(arr_1d)
type(arr_1d)
arr_1d.ndim

[1 2 3 4]


1

In [2]:
import numpy as np
arr_2d = np.array([[1,2,3,4],[5,6,7,8]])
print(arr_2d)
arr_2d.ndim
print ("Size of 2d array is ", arr_2d.size)
print ("The row & column of an array is: ", arr_2d.shape)
print("The datatype of an array is :", arr_2d.dtype)

[[1 2 3 4]
 [5 6 7 8]]
Size of 2d array is  8
The row & column of an array is:  (2, 4)
The datatype of an array is : int32


In [3]:
arr_2d

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [4]:
mx = np.ones(5)
print(mx)
print("DataType is : ", mx.dtype)

[1. 1. 1. 1. 1.]
DataType is :  float64


In [5]:
mx2 = np.ones((5,2))
print(mx2)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [6]:
mx3 = np.ones((4,5), dtype = int)
print(mx3)


[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [7]:
mx4 = np.zeros((2,3), dtype=bool)
print(mx4)

[[False False False]
 [False False False]]
