Random Sampling with Numpy

In [116]:
import numpy as np
import random

In [154]:
# To find the number betweeen 0 to 1
np.random.random(3)

array([0.48472444, 0.14744678, 0.58573091])

In [ ]:
# Random integer matrix (4,5)
np.random.randint(1,5, (4,5))

array([[1, 2, 3, 2, 3],
       [3, 2, 4, 2, 4],
       [4, 2, 4, 4, 1],
       [2, 2, 3, 2, 3]])

In [ ]:
# Random 3D array
random.seed(100)
np.random.randint(1,5, (1,3,3))

array([[[3, 2, 4],
        [3, 2, 3],
        [2, 4, 2]]])

In [ ]:
# To find the integer number between 0 to 5 (but 5 is exclusive)
np.random.randint(1,5)

1

In [166]:
np.random.rand(3)

array([0.13556944, 0.77006919, 0.13770098])

In [192]:
np.random.rand(5)

array([0.07613092, 0.67545624, 0.42771603, 0.53429747, 0.86646034])

In [204]:
# Choose single item
x = [10,20,30,40]
np.random.choice(x)

40

In [217]:
# Choose using for looop
for i in range(10):
    print(np.random.choice(x))

40
40
10
10
40
30
20
10
30
40


In [227]:
np.random.permutation(x)

array([40, 20, 30, 10])